baseURL = "https://tuyentran05.netlify.app"
languageCode = "en-us"
title = "My blog"
theme = "m10c"  

DefaultContentLanguage = "fr"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"
[[params.social]]
  name = "github"
  url = "https://github.com/tuyentran0500"
  avatar = "avatar.jpg"
[[params.social]]
  name = "facebook"
  url = "https://www.facebook.com/WCTHV/"  
[[params.social]]
  name = "instagram"
  url = "https://www.instagram.com/tbtuyen0500/"
[params]
  author = "Trần Bá Tuyên"
  avatar = "https://avatars3.githubusercontent.com/u/49382248?s=400&u=4a86465b75672d4ed670aa83aa14726e241cd5c5&v=4"
  description = "Just a boy tries to do grown-up stuffs"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  featured_image = "/images/batman.jpg"
  recent_posts_number = 2
